#!/bin/sh

ADHOC_INTERFACE=wlan0

echo "Prepare network interface.."
rfkill unblock wlan;
sleep 1;
ip link set ${ADHOC_INTERFACE} down;
sleep 1;
ip link set ${ADHOC_INTERFACE} up;
ifconfig ${ADHOC_INTERFACE} up;
echo "Done!
Create the Ad-hoc network"
iw dev ${ADHOC_INTERFACE} set type ibss;
iw dev ${ADHOC_INTERFACE} ibss join mesh 2437;
echo "Done!
get MAC to generate hopefully unique IP address with, by using the last two
hex pairs as the last two hex pairs for the IP address, converting the hex
to decimal first."
MAC=`/sbin/ip address show  ${ADHOC_INTERFACE}| grep -i "link/ether" | awk '{ print $2 }'`
MAC5=`echo $MAC | cut -d : -f 5`
MAC6=`echo $MAC | cut -d : -f 6`
ip3=`printf %d 0x$MAC5`
ip4=`printf %d 0x$MAC6`
net=172.29
ip=$net.$ip3.$ip4
/sbin/ip address replace $ip/16 broadcast $net.255.255 dev ${ADHOC_INTERFACE}
sleep 1
echo "Done!
The IP used in this node will be: $ip
To be ready for mesh you have to start a routing service, Olsr daemon with: /usr/sbin/olsrd &> /dev/null &"
# OLSR needs port 698 to transmit state messages.
#iptables -A INPUT -p udp --dport 698 -j ACCEPT
#iptables -A INPUT -p tcp -m tcp --dport 2006 -j ACCEPT
# OLSR info need 8088 for http
#iptables -A INPUT -p tcp -m tcp --dport 8088 -j ACCEPT
